# Generated by Django 5.0.2 on 2024-05-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_id', models.CharField(max_length=100)),
                ('date_log', models.DateField()),
                ('am_in', models.TimeField(blank=True, null=True)),
                ('am_in_mask', models.CharField(blank=True, max_length=100, null=True)),
                ('am_out', models.TimeField(blank=True, null=True)),
                ('am_out_mask', models.CharField(blank=True, max_length=100, null=True)),
                ('pm_in', models.TimeField(blank=True, null=True)),
                ('pm_in_mask', models.CharField(blank=True, max_length=100, null=True)),
                ('pm_out', models.TimeField(blank=True, null=True)),
                ('pm_out_mask', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
