# Generated by Django 5.0.2 on 2024-05-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='id',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='am_in',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='am_in_mask',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='am_out',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='am_out_mask',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='employee_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='pm_in',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='pm_in_mask',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='pm_out',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='pm_out_mask',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='remarks',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
